env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: ""

addons:
  coverity_scan:
    project:
      name: "zsx/r3"
      description: "Build submitted via Travis CI"
    notification_email: zeng.shixin@gmail.com
    build_command_prepend: ""
    build_command:   "cd make && make -f makefile-64 -j 4 r3-view-linux"
    branch_pattern: coverity_scan
